services:
  nominatim:
    image: mediagis/nominatim:4.3
    container_name: nominatim-test
    ports:
      - "8080:8080"
    environment:
      - NOMINATIM_PBF_URL=https://github.com/davixde/osm-italy-routing-labels/releases/download/v1.0.0/italia_leggera.osm.pbf
      - NOMINATIM_FLATNODE_FILE=/var/lib/nominatim/flatnode.file
    volumes:
      - nominatim-data:/var/lib/nominatim
    shm_size: '1gb'
    restart: always

volumes:
  nominatim-data:
