name: Build

on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch: # "Run workflow" manual trigger

# Permissions to allow writing to the repository contents for creating releases
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il codice del repository
        uses: actions/checkout@v4

      - name: Imposta la data corrente
        id: date
        run: echo "today=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Installa Osmium Tool nativo
        run: |
          sudo apt-get update
          sudo apt-get install -y osmium-tool

      - name: Scarica l'estratto dell'intera Italia da Geofabrik
        run: |
          echo "░░░| Download di italy-latest.osm.pbf..."
          curl -L --retry 3 -o italia.osm.pbf https://download.geofabrik.de/europe/italy-latest.osm.pbf
          echo "█░░| Download completato."

      - name: Filtra la mappa con Osmium
        run: |
          echo "██░| Avvio del filtraggio della mappa..."
          osmium tags-filter italia.osm.pbf w/highway r/boundary=administrative r/boundary=postal_code nwr/place nwr/addr:* -o italia_leggera.osm.pbf --overwrite
    
          echo "███| Resoconto dimensioni:"
          ls -lh italia.osm.pbf italia_leggera.osm.pbf

      - name: Pulizia file temporanei
        run: rm -f italia.osm.pbf

      - name: Pubblica il file nelle GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: italia_leggera.osm.pbf
          tag_name: "latest"
          name: "File mappa"
          body: |
            📅 **Data di generazione:** ${{ steps.date.outputs.today }}
            🏃 **Runner:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          draft: false
          prerelease: false
          make_latest: true
